/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LeaguetableImport } from './routes/leaguetable'
import { Route as FixturetableImport } from './routes/fixturetable'
import { Route as FantasyImport } from './routes/fantasy'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LeaguetableRoute = LeaguetableImport.update({
  id: '/leaguetable',
  path: '/leaguetable',
  getParentRoute: () => rootRoute,
} as any)

const FixturetableRoute = FixturetableImport.update({
  id: '/fixturetable',
  path: '/fixturetable',
  getParentRoute: () => rootRoute,
} as any)

const FantasyRoute = FantasyImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyImport
      parentRoute: typeof rootRoute
    }
    '/fixturetable': {
      id: '/fixturetable'
      path: '/fixturetable'
      fullPath: '/fixturetable'
      preLoaderRoute: typeof FixturetableImport
      parentRoute: typeof rootRoute
    }
    '/leaguetable': {
      id: '/leaguetable'
      path: '/leaguetable'
      fullPath: '/leaguetable'
      preLoaderRoute: typeof LeaguetableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/fixturetable': typeof FixturetableRoute
  '/leaguetable': typeof LeaguetableRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/fixturetable': typeof FixturetableRoute
  '/leaguetable': typeof LeaguetableRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/fixturetable': typeof FixturetableRoute
  '/leaguetable': typeof LeaguetableRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fantasy' | '/fixturetable' | '/leaguetable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fantasy' | '/fixturetable' | '/leaguetable'
  id: '__root__' | '/' | '/fantasy' | '/fixturetable' | '/leaguetable'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FantasyRoute: typeof FantasyRoute
  FixturetableRoute: typeof FixturetableRoute
  LeaguetableRoute: typeof LeaguetableRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FantasyRoute: FantasyRoute,
  FixturetableRoute: FixturetableRoute,
  LeaguetableRoute: LeaguetableRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fantasy",
        "/fixturetable",
        "/leaguetable"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fantasy": {
      "filePath": "fantasy.tsx"
    },
    "/fixturetable": {
      "filePath": "fixturetable.tsx"
    },
    "/leaguetable": {
      "filePath": "leaguetable.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
